apiVersion: v1
kind: Service
metadata:
  name: k0420-prd-ms-inova-mais-back
  namespace: default # Replace with your assigned namespace
  labels:
    app: k0420-prd-ms-inova-mais-back
    tier: backend
spec:
  selector:
    app: k0420-prd-ms-inova-mais-back
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      name: http
  type: ClusterIP
