apiVersion: v1
kind: Service
metadata:
  # Naming Convention: <sid>-<region>-<app_name>-<api_version>
  name: K0418-prd-inovaflow-v1
  namespace: default # Replace with your assigned namespace
spec:
  selector:
    app: K0418-prd-inovaflow-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
