apiVersion: v1
kind: Service
metadata:
  name: KXXXX-prd-inovaflow-backend-v1
  namespace: default # Replace with your assigned namespace
  labels:
    app: KXXXX-prd-inovaflow-backend-v1
    tier: backend
spec:
  selector:
    app: KXXXX-prd-inovaflow-backend-v1
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      name: http
  type: ClusterIP
